### ISSUE TITLE
How to remove uploaded file

### ISSUE THREAD

**Issue by ilgincamoglu** [Bunlong/react-papaparse#11]
Hi! I am using CSVReader Click and Drag upload. I want to have a functionality to cancel uploaded file. Meaning when I click an another button I want uploaded file to be removed from CSVReader. Is there such functionality? I couldn't find it

**Comment by Bunlong** [comment]
@ilgincamoglu `react-papaparse` version 3.0.3 has been released with cancel or remove functionality. Please kindly check. Could we close the issue? Thanks!

**Comment by ilgincamoglu** [comment]
Yes this is great, thanks!

**Comment by Bunlong** [comment]
You are welcome. Thank you so much for the feedback and contribution. Thanks!
