### ISSUE TITLE
Changing header in the config does not seem to be working

### ISSUE THREAD

**Issue by jadenmazzone** [Bunlong/react-papaparse#115]
Adding header in the config set to true does not seem to do anything...

```
const { CSVReader } = useCSVReader();    
<CSVReader
    config={{header:true}}
  
>
```

Version 4.0.0

**Comment by jonstacks** [comment]
@Bunlong, thanks for fixing this so fast. I just updated to 4.0.1 and passing in the header config is working for me now.

**Comment by Bunlong** [comment]
@jonstacks, my pleasure!
