### ISSUE TITLE
props to add the input element

### ISSUE THREAD

**Issue by hussamkhatib** [Bunlong/react-papaparse#123]
I am adding the CSVReader component in a form element and want to pass an required attribute to the input tag via props.

**Comment by Bunlong** [comment]
@hussamkhatib Could you please put the sample code in comment?

**Comment by hussamkhatib** [comment]
Hey @Bunlong,
Can you assign this to me? I would like to finish this up.

**Comment by Bunlong** [comment]
Hi @hussamkhatib 

Please Fork and make a Pull request. Thanks!
