### ISSUE TITLE
Maybe it would be better to make jsonToCSV also work like a pure function.

### ISSUE THREAD

**Issue by s5s5** [Bunlong/react-papaparse#135]
Hi, thanks for your great work, I have a problem when I upgraded from V3 to V4.
I used `jsonToCSV` as a pure function in V3 and he worked fine, but upgrading to V4, `jsonToCSV` became a hook, which restricts it and it can't be used in I suggest to put `jsonToCSV` and some other pure functions without restricting it to a hook.
Thanks.

**Comment by Bunlong** [comment]
@s5s5 Okay, I got it. I going to add `jsonToCSV` as a pure function in next version in next week. Thanks!
