### ISSUE TITLE
Enhancement: Await `data` function in `CSVDownloader`

### ISSUE THREAD

**Issue by JakeHaitsma** [Bunlong/react-papaparse#146]
I have a scenario where I want a download button (`CSVDownloader`) to trigger and await an asynchronous data fetch before downloading the CSV.
Currently, I am rendering two components (one to kick off the data request and `CSVDownloader` to download once that data has been retrieved. It would be nice if `CSVDownloader` awaited `data` when it is provided as a function so the extra component was unnecessary.

```javascript
<CSVDownloader
  filename={'filename'}
  data={async () => {
    // fetch some data, set loading state, etc
    await new Promise(resolve => setTimeout(resolve, 1000));

    return [
      {
        "Column 1": "1-1",
        "Column 2": "1-2",
        "Column 3": "1-3",
        "Column 4": "1-4",
      }
    ]}
  }
>
  Download
</CSVDownloader>
```

**Comment by crice88** [comment]
Could really use this feature. Any ideas on a timeline?

**Comment by danwdart** [comment]
Is there a workaround?

**Comment by ricejons** [comment]
any news of this merge @Bunlong ?

**Comment by Bunlong** [comment]
The feature was added in latest version. Thanks!
