### ISSUE TITLE
Preview Config Option Causes Data Not To Load

### ISSUE THREAD

**Issue by timtutt** [Bunlong/react-papaparse#15]
Hi - 

Just started toying around with react-papaparse, and was trying to pass in the `preview` options into the config for papa parse like below:

```javascript
<CSVReader
              onDrop={this.handleOnDrop}
              onError={this.handleOnError}
              addRemoveButton
              onRemoveFile={this.handleOnRemoveFile}
              config={{
                header: this.state.hasHeaderRow,
                dynamicTyping: true,
                preview: 1000
              }}
              style={{minHeight: "200px"}}
            >
```

Unfortunately when `preview` is passed my `handleOnDrop` function is never called. When I remove that option everything works as expected. Am I missing something with this particular functionality?

**Comment by Bunlong** [comment]
@timtutt I will fix it, when it done I will let you know. Thanks!

**Comment by Eptis** [comment]
Having the same issue but without drag-and-drop. Let me know If I can help fix it.

**Comment by Bunlong** [comment]
@Eptis Yes, you can help to fix it.

**Comment by Bunlong** [comment]
@timtutt @Eptis react-papaparse version 3.1.2 has been released with fixing `Preview Config Option Causes Data Not To Load`. Please kindly check. Could we close the issue? Thanks!

**Comment by timtutt** [comment]
Just updated locally, tested and verified! Thanks much.

**Comment by Bunlong** [comment]
@timtutt You are welcome. Thanks!
