### ISSUE TITLE
worker:false doesn't work

### ISSUE THREAD

**Issue by garhul** [Bunlong/react-papaparse#152]
Since there's a bug with `worker:true` and `transformHeader` I'm forced to use `worker:false` for readString function.

The type at @types/papaparse for config forces worker to be true for readString function. 
Using papaparse package directly instead of react-papaparse allowed me to get the config working with `papa.parse` function.

here's the offending line.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/papaparse/index.d.ts#L276

**Comment by vsnthdev** [comment]
I'm also have the same issue, switching to `papa.parse` for now 🤞
