### ISSUE TITLE
downloadRequestHeaders config does not work

### ISSUE THREAD

**Issue by SananGuliyev** [Bunlong/react-papaparse#17]
Hi,

I am trying to read data from s3 and due to CORS I have to add `Origin` header but it looks like it's not setting the header as expected in Chrome. I now it should be added by default by browser but I do not see any origin header in the network tab.

Chrome: does not work
Safari: Refused to set unsafe header "Origin"
Opera: works but gives error `papaparse.js:699 Refused to get unsafe header "Content-Range"`

```
readRemoteFile(
    'https://some-s3.url.com/sample.csv',
    {
        downloadRequestHeaders: {
            'Origin': 'http://example.com/'
        },
        step: (row) => {
            console.log('Row:', row.data)
        },
        complete: (results) => {
            console.log('Results:', results)
        }
    }
);
```

Thanks in advance.

**Comment by Bunlong** [comment]
@SananGuliyev The problem is you haven't  allowed origin header on amazon s3. You can follow this [guidance](https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error) to solve this problem. If it works please let me know. Thanks!

**Comment by SananGuliyev** [comment]
I already added the CORS configuration to S3. It's an issue on Chrome level. I disabled out of blink on Chrome and it's gone. 

Do you have any idea about `Refused to get unsafe header "Content-Range"` this error?

**Comment by Bunlong** [comment]
@SananGuliyev Could you please follow this [guidance](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html) and try the following CORES configuration:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin><!-- insert your origin here --></AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>Range</AllowedHeader>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>Accept-Ranges</ExposeHeader>
    <ExposeHeader>Content-Range</ExposeHeader>
    <ExposeHeader>Content-Encoding</ExposeHeader>
    <ExposeHeader>Content-Length</ExposeHeader>
    <AllowedHeader>Authorization</AllowedHeader>
  </CORSRule>
</CORSConfiguration>
```

**Comment by SananGuliyev** [comment]
Thanks. I will try to expose headers, too.

**Comment by Bunlong** [comment]
@SananGuliyev Yes, you are welcome. Thanks!
