### ISSUE TITLE
dark mode cannot read default template

### ISSUE THREAD

**Issue by bugzpodder** [Bunlong/react-papaparse#24]
<img width="898" alt="Screen Shot 2020-05-16 at 12 23 46 PM" src="https://user-images.githubusercontent.com/14841421/82128448-291b2e80-9770-11ea-9b56-c5e287c5fab4.png">

Also, can we optionally disable progressbar and fileSize?

**Comment by Bunlong** [comment]
Dear @bugzpodder Thank you so much!

react-papaparse v3.6.0 has been released!

Minor version with the following changes:

* Enable to customize CSVReader (Drag Upload) dropArea style
* Improve docs

Wiki:

* [How to customize CSVReader (Drag to Upload) style?](https://github.com/Bunlong/react-papaparse/wiki/CSVReader-(Drag-to-Upload)-Style)
