### ISSUE TITLE
disable progress bar

### ISSUE THREAD

**Issue by bugzpodder** [Bunlong/react-papaparse#27]
even with child as a function i can't disable to progress bar

**Comment by bugzpodder** [comment]
was able to override complete/step function to remove progress bar

**Comment by Bunlong** [comment]
@bugzpodder Thank you so much for you feedback. Could I add you to the contributors list?

**Comment by bugzpodder** [comment]
ok

**Comment by Bunlong** [comment]
@bugzpodder you are added to contributor list. Thanks!

**Comment by Bunlong** [comment]
@bugzpodder react-papaparse v3.3.0 has been released with `disable progress bar`. Please kindly check. Thanks!

**Comment by bugzpodder** [comment]
thanks!
