### ISSUE TITLE
The Local File demo is not outputting anything in the console

### ISSUE THREAD

**Issue by simon-musy** [Bunlong/react-papaparse#30]
In the demo as well as locally, the following code does not output anything when uploading a file.
```javascript
import React, { Component } from 'react'
import { CSVReader } from 'react-papaparse'

export default class CSVReader2 extends Component {
  handleOnDrop = (data) => {
    console.log('---------------------------')
    console.log(data)
    console.log('---------------------------')
  }

  handleOnError = (err, file, inputElem, reason) => {
    console.log(err)
  }

  handleOnRemoveFile = (data) => {
    console.log('---------------------------')
    console.log(data)
    console.log('---------------------------')
  }

  render() {
    return (
      <>
        <h5>Click and Drag Upload</h5>
        <CSVReader
          onDrop={this.handleOnDrop}
          onError={this.handleOnError}
          addRemoveButton
          onRemoveFile={this.handleOnRemoveFile}
        >
          <span>Drop CSV file here or click to upload.</span>
        </CSVReader>
      </>
    )
  }
}
```
Am I missing something? The string parsing demo works like a charm

**Comment by Bunlong** [comment]
Hi @simon-musy 

I get a try on [codesandbox](https://codesandbox.io/s/react-papaparse-kubj5), it works.

![Screenshot from 2020-06-18 16-40-29](https://user-images.githubusercontent.com/1308397/85005035-75e49180-b182-11ea-99b2-42c701a6f0af.png)

It also work on demo but don't forget to click Parse button.

![Screenshot from 2020-06-18 16-44-35](https://user-images.githubusercontent.com/1308397/85005458-04f1a980-b183-11ea-924d-c8d8d7c741d9.png)

**Comment by simon-musy** [comment]
Hi @Bunlong, my bad, I thought the handleOnDrop was supposed to output something when uploading the file.

Thanks for the quick reply!

**Comment by Bunlong** [comment]
Hi @simon-musy You are very welcome. Thank you so much :bowing_man:
