### ISSUE TITLE
error when running "npm run build"

### ISSUE THREAD

**Issue by mergingseas** [Bunlong/react-papaparse#32]
when running **npm run build** I get the following error:

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-papaparse/dist/react-papaparse.es.js:13:28612 

My setup is using create-react-app and node v8 and node v13 was tried

**Comment by Bunlong** [comment]
@mergingseas Could you please try to install `react-papaparse` v.3.4.0 which is the latest version? Thanks!

**Comment by mergingseas** [comment]
Hi Bunlong, I upgraded to the new version of v3.4 and I still get the same:
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-papaparse/dist/react-papaparse.es.js:13:28612

**Comment by Bunlong** [comment]
@mergingseas I just checked with `create-react-app` and it works in my local. Could you try with node v12.3.1 and npm 6.14.5 ?

**Comment by Olovorr** [comment]
I experience the same issue, did you figure out a workaround / fix for this? I am using the latest (3.7.0) version of paparse and react-scripts 3.4.1. @Bunlong @mergingseas

**Comment by Bunlong** [comment]
@Olovorr What are the create next app version, node version, and npm version in your local environment?

**Comment by Olovorr** [comment]
> @Olovorr What are the create next app version, node version, and npm version in your local environment?

Not create next app, but [create react app (CRA)](https://github.com/facebook/create-react-app). The issue is that when building production build, it expects ES5 syntax and not higher. That being said I already created PR for this so unless you have a problem with my solution we probably don't need to dive deeper on this. As far as I know downgrading compiling target version should not cause any issues.

**Comment by Bunlong** [comment]
@Olovorr Yes, I got your PR. Okay let me test it and I will merge and deploy to production as soon as possible. Thanks you so much, I do appreciate for your help, could I add you to the contributor list?

**Comment by Olovorr** [comment]
> @Olovorr Yes, I got your PR. Okay let me test it and I will merge and deploy to production as soon as possible. Thanks you so much, I do appreciate for your help, could I add you to the contributor list?

Sure mate! 🙂

**Comment by Bunlong** [comment]
@Olovorr react-papaparse v3.7.1 has been released! You were added to contributor list. Thanks!
