### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by takebo** [Bunlong/react-papaparse#34]
Is there a way to customize the styles of the components?
Especially on the drag and drop, i want to customize the box that shows up with the filename, progress bar, etc

**Comment by glinkot** [comment]
Yes, I'm here for the same reason.  Looking at csvreader.tsx, the very narrow width (100px) of the filename box looks strange and I'd like to widen it and get rid of the gradient.  I tried various things like the below, hoping I could modify the dropFile part of the internal 'styles' object, but no success so far.  Any thoughts would be great!

`  const myStyle = {
        dropFile: {
            width: 400
        }
    }
        return (
            <CSVReader
            style={myStyle}
            onError={handleOnError}
                onFileLoad={handleOnFileLoad}
                config={papaConfig}
                addRemoveButton
                onRemoveFile={handleOnRemoveFile}
            >
                <span className="fileDrop">{props.promptText}</span>
            </CSVReader>
        )`

**Comment by Bunlong** [comment]
@takebo @glinkot Well, I will check it and release it for the next version next week. Anyway could I add you in the contributors list?

**Comment by takebo** [comment]
@Bunlong Nice, thank you. Sure, i wouldn't mind.

**Comment by glinkot** [comment]
Sure!  Thanks :)

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by glinkot** [comment]
Hi @Bunlong, any luck putting this small change in?  I'd rather not bugger about forking it just to change that one line 👍.  

My app looks great except for the big weird grey box in the middle...

Thanks for your help

**Comment by Bunlong** [comment]
@glinkot @takebo Please upgrade react-papaparse to latest version (3.5.0) and check the following wiki to customize CSVReader. You were added to contributors list. Thanks!

react-papaparse v3.5.0 has been released!

Minor version with the following changes:

* Enable to customize CSVReader (Drag Upload) dropFile style

Wiki:

* [How to customize CSVReader (Drag Upload) dropFile style?](https://github.com/Bunlong/react-papaparse/wiki/CSVReader-Drag-Upload-dropFile-Style)

**Comment by glinkot** [comment]
Fantastic, thanks so much for that!  I'll check this out tomorrow morning,
looking forward to it.

**Comment by takebo** [comment]
That is awesome @Bunlong ! Thanks alot!

**Comment by Bunlong** [comment]
@takebo @glinkot You are very welcome. Could we close the issue? Thanks!

**Comment by glinkot** [comment]
Yes, for sure.  Thanks again.

**Comment by Bunlong** [comment]
@glinkot You are very welcome. Thanks!
