### ISSUE TITLE
Proposal: Customizable progress bar

### ISSUE THREAD

**Issue by samuelhulla** [Bunlong/react-papaparse#39]
**Proposal**: Customizable progress bar

**Reasoning**: At the moment it feels clunky to only be able to pass boolean to `noProgressBar` and being able to pass `progressBarColor` as the only means of customization since you can't even detect at the moment when the data was actually passed to `onFileLoad` or `onDrop`

- Option 1: **Access progress value directly from child render function**

   The same way you can currently access the file inside the child render function

   Before ⏳ 
   ```js
   <CSVReader>
     {({ file }) => (
        // render
     )}
   </CSVReader>
  ```

   After ⌛ 
   ```js
   <CSVReader>
     {({ file, progress }) => (
        // render
     )}
   </CSVReader>
  ```

- Option 2: **Allow users to pass custom progress bar render callback function**

   This way the users will have greater control as to how the progress bar is displayed

    After ⌛ 
    ```ts
    // CSVReader.tsx
 
    type Props = {
      // optional, defaults to existing one
      renderProgressBar?: (...args: any[]) => (progress: number) => JSX.Element
    }

    // later in render method
    render () {

       const { renderProgressBar } = this.props
       const { progressBar } = this.state 

       return (
          // other stuff
         { progressBar 
            ? renderProgressBar(progressBar)
            : <ProgressBar />
         }
       )
    }
  ```

This way the users could customize the progress bar without introducing breaking changes to the existing implementation while making it more flexible.

**Comment by Bunlong** [comment]
@samuelhulla Do you have some ideas of dropFile style?

**Comment by samuelhulla** [comment]
@Bunlong  sorry, what exactly do you mean by "idea of dropFile style" ?

**Comment by Bunlong** [comment]
@samuelhulla It's okay, That's good proposal. We will implement it for the next version or you can join us to implement it. Could I add you in the contributor list?

**Comment by samuelhulla** [comment]
@Bunlong  Yeah sure why not.

**Comment by Bunlong** [comment]
@samuelhulla I do appreciate your help and we will merge into the master for next release/version. You are added to the contributor list. Thank you so much!
