### ISSUE TITLE
How to use config options with readRemoteFile?

### ISSUE THREAD

**Issue by Quafadas** [Bunlong/react-papaparse#4]
I can't get this to work. 

Any hints?

`        const configOptions = {header: true, dynamicTyping: true};

        readRemoteFile(
            default, configOptions,
            {
                complete: function (results) {
                    console.log(results);
                    console.log(results.data[0]);
                    console.log(results.data[1]);
                }
            }
        )`

Gets me back data with the header in ...

**Comment by Bunlong** [comment]
@Quafadas please try the following format. Thanks!

```javascript
readRemoteFile(bigFileURL, {
    worker: true,
    header: true,
    dynamicTyping: true,
    complete: function(results) {
        console.log(results)
    }
})
```

**Comment by Bunlong** [comment]
@Quafadas if it work please kindly let us know. Thanks!

**Comment by Quafadas** [comment]
Yes!

Worked great. Thanks :-).

**Comment by Bunlong** [comment]
@Quafadas You are very welcome. Thanks :-)
