### ISSUE TITLE
Customise dropArea

### ISSUE THREAD

**Issue by pleavitt** [Bunlong/react-papaparse#40]
Can you add the ability to customise the dropArea using the style prop?

**Comment by Bunlong** [comment]
@pleavitt Thank you so much! Yes, I will implement it for the next version and will be released on Monday. Could I add you to the contributors list?

**Comment by gtupak** [comment]
Also looking forward to this! 🙌

**Comment by Bunlong** [comment]
@pleavitt @gtupak Please upgrade react-papaparse to latest version (3.6.0) and check the following wiki to customize CSVReader style. Thanks! Could I add you to the contributors list?

react-papaparse v3.6.0 has been released!

Minor version with the following changes:

* Enable to customize CSVReader (Drag Upload) dropArea style
* Improve docs

Wiki:

* [How to customize CSVReader (Drag to Upload) style?](https://github.com/Bunlong/react-papaparse/wiki/CSVReader-(Drag-to-Upload)-Style)
