### ISSUE TITLE
Changing highlight color

### ISSUE THREAD

**Issue by OleSkaar** [Bunlong/react-papaparse#54]
Hi! Love papa parse, it's super easy to use. However, I've been struggling to figure out how to style the border-color attribute of the div aroud the input field when you drag a file over the drag and drop (with the dashed lines). It seems to default to purple. I've tried changing style attributes for the CSVreader component, but I can't seem to find anything that relates to this styling. Am I missing something, or is that hardcoded?

**Comment by Bunlong** [comment]
@OleSkaar Thank you for your contribution. We missed this point we will add it and release it by tomorrow. Could I add you to the contributors list? Thanks!

**Comment by OleSkaar** [comment]
@Bunlong Great! Thanks for the quick response. Feel free to add me to the contributor list :)
