### ISSUE TITLE
Trying to get correct JSON format (`header:true`) of uploaded CSV file 

### ISSUE THREAD

**Issue by grapes323** [Bunlong/react-papaparse#6]
Documentation is not consistent with code. Should be `config` instead of `configOptions` and `onFileLoad` instead of `onFileLoaded`.
Code in Read.me section Header row support
```javascript
<CSVReader
  onFileLoaded={this.handleReadCSV}
  inputRef={this.fileInput}
  style={{display: 'none'}}
  onError={this.handleOnError}
  configOptions={{header: true /* Header row support */ }}
/>
```

**Comment by Bunlong** [comment]
@grapes323 I've updated the docs. Thank you for correction.

**Comment by Bunlong** [comment]
@grapes323 Could we close the issue? Thanks!
