### ISSUE TITLE
using CSVReader is breaking in IE

### ISSUE THREAD

**Issue by HarithaKR** [Bunlong/react-papaparse#62]
![image](https://user-images.githubusercontent.com/23190851/92460906-2bedd380-f1e6-11ea-9b7e-cd06c056e52f.png)
![image](https://user-images.githubusercontent.com/23190851/92460921-327c4b00-f1e6-11ea-8632-4d187c7c83e3.png)
I am using react-papaparse for uploading a csv file in the UI. I use CSVReader component . The page is breaking in IE if I use this component. Screenshot attached. Please assist with this. 

`<CSVReader
                  onFileLoad={this.uploadFile}
                  addRemoveButton={true}
                  onRemoveFile={this.removeImportFile}
                  noProgressBar={true}
                  style={{
                    dropArea: {
                      flex: 1,
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      padding: "8px 20px",
                      borderWidth: "1px",
                      borderRadius: "5px",
                      borderColor: "#515151",
                      borderStyle: "dashed",
                      backgroundColor: "#fff",
                      outline: "none",
                      height: "auto",
                      transition: "border .24s ease-in-out",
                      cursor: "pointer",
                      overflow: "hidden",
                    },
                    dropFile: {
                      width: "auto",
                      maxWidth: "200px",
                      fontSize: "12px",
                      lineHeight: "16px",
                      height: 50,
                      borderRadius: "5px",
                      overflow: "hidden",
                      padding: "10px",
                    },
                    fileNameInfo: {
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      maxWidth: "150px",
                    },
                    removeButton: {
                      color: "#828282",
                    },
                  }}
                >
                  <span className="item-content">
                    <div className="item-title">Upload CSV file</div>
                    <div className="item-sub-text">
                      Drag & drop your file or select your file by clicking
                      here.
                    </div>
                  </span>
                </CSVReader>`

**Comment by Bunlong** [comment]
Internet Explorer is no longer supported so I would like to close this issue.
