### ISSUE TITLE
BOM byte for opening CSV in Excel with UTF8

### ISSUE THREAD

**Issue by karland** [Bunlong/react-papaparse#63]
Hi, thanks for `react-papaparse`. 

After discussing it at https://github.com/mholt/PapaParse/issues/830, I wonder, if you would be willing to add an option for a BOM byte, so that Excel recognizes the CSV directly as UTF8. `react-csv-downloader` is doing it [here](https://github.com/dolezel/react-csv-downloader/blob/038af24fcea3a281f24ff42bb66e40eb3d0bd31d/src/index.tsx#L42-L43), but I would like to move to `react-papaparse` because I also would need the upload functionality.

The API could be

```JS
<CSVDownloader
  data={data}
  filename={'filename'}
  type={'link'}
  bom={true}
>
  Download
</CSVDownloader>
```

Thanks a lot.

**Comment by Bunlong** [comment]
@karland Okay, I got it. I will add it as soon as possible; In the week maybe. When done I will let you know. Thanks :pray:

**Comment by karland** [comment]
@Bunlong Wow, great, this is awesome. Thanks a lot.
