### ISSUE TITLE
Add props to change accept type on input element

### ISSUE THREAD

**Issue by toantt28** [Bunlong/react-papaparse#69]
Hi, Your repo is great.
But when I'm using this on different OS that I found a bug
This is hard code so it hard for me to change accept type
`accept="text/csv"`
Above Code work fine on MacOS

But on Window10 / Ubuntu it should be this
`accept=".csv, application/vnd.ms-excel, text/csv"`

Could you make a change let user can change it as props?

**Comment by Bunlong** [comment]
@toantt28 react-papaparse v3.10.0 has been released with accept property is a property to be used to set MIME type for CSV. Default is 'text/csv, .csv, application/vnd.ms-excel'. I would like to close the issue. Thanks!
