### ISSUE TITLE
API change with minor version upgrade

### ISSUE THREAD

**Issue by seanblonien** [Bunlong/react-papaparse#8]
I recently updated my npm packages and react-paparse updated from version 2.0.2 to version 2.1.3. 

The problem is the minor update is very non-compliant with the [NPM versioning](https://docs.npmjs.com/about-semantic-versioning).

The props changed for the CSVReader component and was not backwards compatible (which it should be if only updating minor version).

**Comment by Bunlong** [comment]
@seanblonien We made changes on some features and props name to be consistent with the components and we did not made changes the whole of the API the reason why we decided only updating minor version. Anyway we corrected it. Thank you so much for your feedback and contribution. Thanks!

**Comment by seanblonien** [comment]
Ok great, thanks!
