### ISSUE TITLE
CSVDownload - Writing out a # causes crash - Bug?

### ISSUE THREAD

**Issue by jqrtr** [Bunlong/react-papaparse#80]
I'm creating a CSVDownload and notice if any of my data has a # at the start of the string, it crashes (well, the file output stops at the # character).

See here - File terminates where it should have written out '#123456'
![image](https://user-images.githubusercontent.com/54841915/114561896-ea367700-9c65-11eb-96ac-50020754e972.png)

If I remove the # from the string in my data generation, the file generates fully.

NOTE: Using v3.12.0

**Comment by Bunlong** [comment]
@jqrtr react-papaparse v3.12.1 has been released. It has been fixed. You were added in contributors list. Thank you so much!
