### ISSUE TITLE
CSVReader state updated after file load, even if noProgressBar is true

### ISSUE THREAD

**Issue by stefee** [Bunlong/react-papaparse#88]
We encountered this error in our project:

<img width="1528" alt="Screenshot 2021-06-08 at 1 28 46 pm" src="https://user-images.githubusercontent.com/18026180/121188142-b8eeb780-c860-11eb-8176-bb091495c10b.png">

We tracked down the error to the user closing a file loading modal too quickly after loading the file, because the CSVReader was updating internal state using `setTimeout`.

We expected that setting `noProgressBar` would resolve this bug since the problem was progress bar state updating after the component was unmounted.

**Comment by sophiabarclay** [comment]
I see the noProgressBar bar has been removed in recent versions. Is there a workaround for this warning on the latest version?

**Comment by callum-fairbairn-cazoo** [comment]
Is there any update on this?
