### ISSUE TITLE
Typescript definition support

### ISSUE THREAD

**Issue by apoorvmote** [Bunlong/react-papaparse#9]
I get following error when I import
```
Could not find a declaration file for module 'react-papaparse'. '/home/apoorvmote/import-export/node_modules/react-papaparse/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-papaparse` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-papaparse';`ts(7016)
```

**Comment by AgmarTorres** [comment]
Please, try this in package.json :
 Update:
  "main": "dist/index.js",
To:
"main": "dist/index"

**Comment by apoorvmote** [comment]
I am using 2 different other libraries at the moment. One for reading csv and one for exporting csv. They both have typescript support. But would love to just use one instead of two. So not looking for hacky solution. I will wait for `@types/react-papaparse`

**Comment by Bunlong** [comment]
@apoorvmote @AgmarTorres react-papaparse v3.2.1 has been released which support both JavaScript & TypeScript. Thanks!

**Comment by Bunlong** [comment]
@apoorvmote @AgmarTorres Could we close this issue? Thanks!
